version: '3.3'

services:
  lettuce-wordle:
    build: .
    container_name: lettuce-wordle
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
networks:
  default:
    external:
      name: nginx
