version: "2"
services:
  node:
    image: "node:17"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/lettucebowler/repo/lettuce-wordle/:/home/node/app
    expose:
      - "3000"
    command: "npm run dev"