name = "lettuce-wordle"
compatibility_date = "2024-10-22"

[[ d1_databases ]]
binding = "WORDLETTUCE_DB"
database_name = "wordlettuce"
database_id = "818c950f-7cbd-43b9-8f05-e6a230d06fe0"

[env.prod]
routes = [
  { pattern = "word.lettucebowler.net", custom_domain = true }
]